server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:client_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Activer la console H2 pour les tests locaux
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
